version: "2"
services:
  test-app:
    image: tebieto/autoscout24-listing-report:v1.0.0
    container_name: test-app
    build:
      context: .
    ports:
      - "5000:5000"
    environment:
      - PORT=5000
      - NODE_ENV=development
